### ISSUE TITLE
State of Current Implementation

### ISSUE THREAD

**Issue by pclucas14** [rosinality/vq-vae-2-pytorch#1]
Hi, 

I was wondering if you had any results to share yet (samples, or held-out likelihood) to assess performance. I was planning on implementing the paper, but it seems you are already done! I would be happy to contribute to your repository if you want some extra hands

Thanks, 
Lucas

**Comment by rosinality** [comment]
Hello,

VQ-VAE (Stage 1) training is done and it seems work well. But stage 2 training is quite heavy and I don't have enough resources...But I have trained small model few epochs and I think it works.

**Comment by pclucas14** [comment]
ok great! closing issue
