### ISSUE TITLE
Latent maps sizes

### ISSUE THREAD

**Issue by takada-lmd** [rosinality/vq-vae-2-pytorch#14]
Thank you for implementing this in pytorch.
According to the paper (Generating Diverse High-Fidelity Images with VQ-VAE-2), the input to the model is a 256 × 256 image that is compressed to quantized latent maps of size 64 × 64 and 32 × 32 for the bottom and top levels, respectively.
In this code, the size of latent maps for the bottom and top levels (quant_b and quant_t) can be seen 2 × 64 × 64 × 64 and 2 × 64 × 32 × 32 respectively.

Please tell me the meanings of the additional parts (2 × 64). 
How can I convert quant_b and quant_t to 64 × 64 and 32 × 32?

**Comment by phongnhhn92** [comment]
If i am not wrong then that number 2 is the number of batch size you have set during training ?

**Comment by rosinality** [comment]
quant_t & quant_b is not an discrete codes, rather it is embedded vectors of it. So it have additional dimensions (64). What corresponds to discrete latent codes is id_t & id_b vectors. It should shaped as 32 x 32 and 64 x 64. You can get these codes by using VQVAE.encode.

**Comment by takada-lmd** [comment]
Thank you for your quick response.
solved!
