### ISSUE TITLE
The hardware required.

### ISSUE THREAD

**Issue by nobodypengium** [rosinality/vq-vae-2-pytorch#16]
Thanks for your implementation.
Could you tell me some details about the nums of GPUs you used, the training duration on your platform, and the memory occupied?
Thanks!

**Comment by rosinality** [comment]
I have trained VQ-VAE with 1 P40. I don't remember training duration well, but it can be trained in short times.
PixelSNAIL trained with 3-4 V100s with mixed precision training, and training duration was 3-5 days.

**Comment by nobodypengium** [comment]
Thanks a lot for your reply!
