### ISSUE TITLE
Is q_latent_loss missing?

### ISSUE THREAD

**Issue by nimaous** [rosinality/vq-vae-2-pytorch#17]
Hi 
I was comparing your code with the original TensorFlow code made by the authors. It seems you
are not considering q_latent_loss in your Quantize class (check line 101 of https://github.com/deepmind/sonnet/blob/master/sonnet/python/modules/nets/vqvae.py)  
Am I missing something?

**Comment by airalcorn2** [comment]
For anyone else who has the same question, it looks like the port is implementing [`VectorQuantizerEMA`](https://github.com/deepmind/sonnet/blob/master/sonnet/python/modules/nets/vqvae.py#L124).
