### ISSUE TITLE
Training procedure?

### ISSUE THREAD

**Issue by gslaller** [rosinality/vq-vae-2-pytorch#19]
Acc. to the paper the Algorithm goes as follow:
~~~~
....
h_top <- Etop(x)
e_top <- Quantize(h_top)

h_bottom <- Ebottom(x, e_top)
e_bottom -< Quantize(h_bottom)
~~~~

I thing that you have implemented the code as follow(in vqvae.py)
~~~~
....
h_bottom <-  Ebottom(e_top)
e_bottom <- Quantize(h_bottom)
.....
~~~~
thus excluding `x` in `Ebottom` as a prior. You clearly have fine end results, I just wanted to ask whether it is even important to include it.

**Comment by rosinality** [comment]
It is implemented as follows:

```python
e_bottom = E_bottom(x)
e_top = E_top(e_bottom)
q_top = Quantize(e_top)
d_top = D_top(q_top)
q_bottom = Quantize(d_top, e_bottom)
```

So E_bottom will also depend on x. (shared with E_top).

**Comment by gslaller** [comment]
I had confused something from the paper. But thanks for the reply.
