### ISSUE TITLE
AttributeError: module 'torch.nn.functional' has no attribute 'one_hot'

### ISSUE THREAD

**Issue by cdq14** [rosinality/vq-vae-2-pytorch#2]
thanks for this work! But i still have a question:

When I run the code train_vqvae.py, it will report an error 
"AttributeError: module 'torch.nn.functional' has no attribute 'one_hot'"

**Comment by wangxiaodong1021** [comment]
This needs pytorch > 1.1.0

**Comment by cdq14** [comment]
> This needs pytorch > 1.1.0

thanks ! solved.
