### ISSUE TITLE
How To Generate Images

### ISSUE THREAD

**Issue by impulsecorp** [rosinality/vq-vae-2-pytorch#29]
What command do I run to generated images using your pretrained model?
I tried various methods such as 
python3 sample.py --vqvae --top test.jpg
but could not figure it out.

**Comment by TWJubb** [comment]
Try

```
python3 sample.py --batch=32 --top=pixelsnail_top_<N>.pt --bottom=pixelsnail_bottom_<N>.pt --vqvae=vqvae_<N>.pt test.jpg
```

where you replace `<N>` with the relevant number; pointing these arguments to the checkpoint of three models you've trained to get to this point.

**Comment by qoo5oop** [comment]
I am sorry for hijacking but would you please give me a advice?
I could get only pixelsnail_top_<N>.pt but not pixelsnail_bottom_<N>.pt.
Can I generate the image without pixelsnail_bottom_<N>.pt?

**Comment by WoshiBoluo** [comment]
> Try
> 
> ```
> python3 sample.py --batch=32 --top=pixelsnail_top_<N>.pt --bottom=pixelsnail_bottom_<N>.pt --vqvae=vqvae_<N>.pt test.jpg
> ```
> 
> where you replace `<N>` with the relevant number; pointing these arguments to the checkpoint of three models you've trained to get to this point.

Hi, how to generate images just using vqvae1 ?
