### ISSUE TITLE
Error when running Pixel Snail on a custom dataset  

### ISSUE THREAD

**Issue by xandernewton** [rosinality/vq-vae-2-pytorch#41]
Hi there, I've been trying to run pixel snail on a custom dataset. Firstly I run:

```python train_vqvae.py ./dataset --size 128```

with a size of 128 as my GPU only has 8GB of memory. Then extract the codes using:

``` python extract_code.py --ckpt checkpoint/vqvae_560.pt --name small128 --size 128 ./dataset```

And then finally running:

```python train_pixelsnail.py small128```

However I always encounter this error:

```RuntimeError: The expanded size of the tensor (16) must match the existing size (32) at non-singleton dimension 3.  Target sizes: [32, 2, 16, 16].  Tensor sizes: [1, 2, 16, 32]```

on line 408: https://github.com/rosinality/vq-vae-2-pytorch/blob/4d2dbc0e073f033675843225dd7436550f9d6a47/pixelsnail.py#L408   

Do I need to change any arguments when running train_pixelsnail.py? Any help would be appreciated.

**Comment by rosinality** [comment]
I have hardcoded image feature map sizes for PixelSNAIL. I think you can change sizes so it corresponds to actual code sizes. https://github.com/rosinality/vq-vae-2-pytorch/blob/master/train_pixelsnail.py#L106 You can change this line to `[16, 16],`

**Comment by xandernewton** [comment]
Thanks, works perfectly!
