### ISSUE TITLE
Top/Bottom unexpected information in Stage1

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [rosinality/vq-vae-2-pytorch#54]
@rosinality 
I trained my model from scratch on the LFW face dataset, but the reconstructions using the top and bottom latent maps does not produce significant information. 
![1](https://user-images.githubusercontent.com/22388014/100975949-cf8c1d00-3564-11eb-92d3-2a2c92e1e994.png)
![Screenshot from 2020-12-03 12-40-46](https://user-images.githubusercontent.com/22388014/100975954-d2870d80-3564-11eb-9ba3-990a270f17e0.png)

How can I finetune this model so that the top and bottom reconstructions are good?

**Comment by rosinality** [comment]
If you want to reconstruct from only with top or bottom codes, then it would be better to use additional reconstruction losses for each of latent maps.

**Comment by SURABHI-GUPTA** [comment]
@rosinality okay.. I will look into this.

**Comment by Raoshijin** [comment]
How do you get the bottom model?after I trained pixelsnail.py I only get the top model and vqvae model

**Comment by rosinality** [comment]
@Raoshijin You can use `--hier bottom` arguments to train bottom level models.
