### ISSUE TITLE
Unable to load the model when training VQVAE with multiple GPUs

### ISSUE THREAD

**Issue by luyvlei** [rosinality/vq-vae-2-pytorch#62]
When using multiple GPUs to train VQVAE, the model checkpoint cannot be loaded when extract_code.
However, this problem does not exist when training with a single GPU, and the saved checkpoint files will be larger when training with multiple GPUs.

My running environment is : torch==1.4.0 python==3.7.0

The following is the error message:
------
python extract_code.py --ckpt checkpoint/vqvae_1000.pt --size 1024 --name crack_mdb ./crack/
Traceback (most recent call last):
  File "extract_code.py", line 60, in <module>
    model.load_state_dict(torch.load(args.ckpt))
  File "/home/lll/anaconda3/envs/ICT_py37_torch14/lib/python3.7/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for VQVAE:
        Missing key(s) in state_dict: "enc_b.blocks.0.weight", "enc_b.blocks.0.bias", "enc_b.blocks.2.weight", "enc_b.blocks.2.bias", "enc_b.blocks.4.weight", "enc_b.blocks.4.bias", "enc_b.blocks.5.conv.1.weight", "enc_b.blocks.5.conv.1.bias", "enc_b.blocks.5.conv.3.weight", "enc_b.blocks.5.conv.3.bias", "enc_b.blocks.6.conv.1.weight", "enc_b.blocks.6.conv.1.bias", "enc_b.blocks.6.conv.3.weight", "enc_b.blocks.6.conv.3.bias", "enc_t.blocks.0.weight", "enc_t.blocks.0.bias", "enc_t.blocks.2.weight", "enc_t.blocks.2.bias", "enc_t.blocks.3.conv.1.weight", "enc_t.blocks.3.conv.1.bias", "enc_t.blocks.3.conv.3.weight", "enc_t.blocks.3.conv.3.bias", "enc_t.blocks.4.conv.1.weight", "enc_t.blocks.4.conv.1.bias", "enc_t.blocks.4.conv.3.weight", "enc_t.blocks.4.conv.3.bias", "quantize_conv_t.weight", "quantize_conv_t.bias", "quantize_t.embed", "quantize_t.cluster_size", "quantize_t.embed_avg", "dec_t.blocks.0.weight", "dec_t.blocks.0.bias", "dec_t.blocks.1.conv.1.weight", "dec_t.blocks.1.conv.1.bias", "dec_t.blocks.1.conv.3.weight", "dec_t.blocks.1.conv.3.bias", "dec_t.blocks.2.conv.1.weight", "dec_t.blocks.2.conv.1.bias", "dec_t.blocks.2.conv.3.weight", "dec_t.blocks.2.conv.3.bias", "dec_t.blocks.4.weight", "dec_t.blocks.4.bias", "quantize_conv_b.weight", "quantize_conv_b.bias", "quantize_b.embed", "quantize_b.cluster_size", "quantize_b.embed_avg", "upsample_t.weight", "upsample_t.bias", "dec.blocks.0.weight", "dec.blocks.0.bias", "dec.blocks.1.conv.1.weight", "dec.blocks.1.conv.1.bias", "dec.blocks.1.conv.3.weight", "dec.blocks.1.conv.3.bias", "dec.blocks.2.conv.1.weight", "dec.blocks.2.conv.1.bias", "dec.blocks.2.conv.3.weight", "dec.blocks.2.conv.3.bias", "dec.blocks.4.weight", "dec.blocks.4.bias", "dec.blocks.6.weight", "dec.blocks.6.bias".
        Unexpected key(s) in state_dict: "module.enc_b.blocks.0.weight", "module.enc_b.blocks.0.bias", "module.enc_b.blocks.2.weight", "module.enc_b.blocks.2.bias", "module.enc_b.blocks.4.weight", "module.enc_b.blocks.4.bias", "module.enc_b.blocks.5.conv.1.weight", "module.enc_b.blocks.5.conv.1.bias", "module.enc_b.blocks.5.conv.3.weight", "module.enc_b.blocks.5.conv.3.bias", "module.enc_b.blocks.6.conv.1.weight", "module.enc_b.blocks.6.conv.1.bias", "module.enc_b.blocks.6.conv.3.weight", "module.enc_b.blocks.6.conv.3.bias", "module.enc_t.blocks.0.weight", "module.enc_t.blocks.0.bias", "module.enc_t.blocks.2.weight", "module.enc_t.blocks.2.bias", "module.enc_t.blocks.3.conv.1.weight", "module.enc_t.blocks.3.conv.1.bias", "module.enc_t.blocks.3.conv.3.weight", "module.enc_t.blocks.3.conv.3.bias", "module.enc_t.blocks.4.conv.1.weight", "module.enc_t.blocks.4.conv.1.bias", "module.enc_t.blocks.4.conv.3.weight", "module.enc_t.blocks.4.conv.3.bias", "module.quantize_conv_t.weight", "module.quantize_conv_t.bias", "module.quantize_t.embed", "module.quantize_t.cluster_size", "module.quantize_t.embed_avg", "module.dec_t.blocks.0.weight", "module.dec_t.blocks.0.bias", "module.dec_t.blocks.1.conv.1.weight", "module.dec_t.blocks.1.conv.1.bias", "module.dec_t.blocks.1.conv.3.weight", "module.dec_t.blocks.1.conv.3.bias", "module.dec_t.blocks.2.conv.1.weight", "module.dec_t.blocks.2.conv.1.bias", "module.dec_t.blocks.2.conv.3.weight", "module.dec_t.blocks.2.conv.3.bias", "module.dec_t.blocks.4.weight", "module.dec_t.blocks.4.bias", "module.quantize_conv_b.weight", "module.quantize_conv_b.bias", "module.quantize_b.embed", "module.quantize_b.cluster_size", "module.quantize_b.embed_avg", "module.upsample_t.weight", "module.upsample_t.bias", "module.dec.blocks.0.weight", "module.dec.blocks.0.bias", "module.dec.blocks.1.conv.1.weight", "module.dec.blocks.1.conv.1.bias", "module.dec.blocks.1.conv.3.weight", "module.dec.blocks.1.conv.3.bias", "module.dec.blocks.2.conv.1.weight", "module.dec.blocks.2.conv.1.bias", "module.dec.blocks.2.conv.3.weight", "module.dec.blocks.2.conv.3.bias", "module.dec.blocks.4.weight", "module.dec.blocks.4.bias", "module.dec.blocks.6.weight", "module.dec.blocks.6.bias".

**Comment by rosinality** [comment]
You can just strip off `'module.'` from state_dict keys, like this:

```python
new_ckpt = {}

for k, v in ckpt.items():
    new_ckpt[k.replace('module.', '', 1)] = v

model.load_state_dict(new_ckpt)
```

**Comment by luyvlei** [comment]
Thanks to @rosinality, it works

**Comment by allenhung1025** [comment]
Thanks to @rosinality, it works for me too!
