### ISSUE TITLE
VQ-VAE-2 with three levels

### ISSUE THREAD

**Issue by vvvm23** [rosinality/vq-vae-2-pytorch#63]
In this repository, it implements a two level VQ-VAE, matching that of Figure 2 in the original paper. 

In the paper it also mentions three level VQ-VAE, as seen in Figure 3. Given your implementation, how would you go about extending it to support three levels?

I have a good idea how this is done for the encoder modules, however for the decoders, it is unclear which latent codes it uses as an input. In particular, does the bottom level decoder take top, middle and bottom codes? Or simply just the bottom and middle (taking the same and preceding level codes as an input)?

Thanks for any help!

**Comment by duxingren14** [comment]
The same question from me. I am not clear about the input dimensions of quant_conv_bottom and decoder. should it be emb_dim+emb_dim+channel. for quant_conv_bottom, and emb_dim+emb_dim+emb_dim for decoder?

**Comment by vvvm23** [comment]
I've been working on my own implementation (you can find it in my profile). It isn't finished yet, but I've got decent results with the quan layer being `emb_dim + channel`  and the decoder being `emb_dim*3`.

I'm not sure if this is entirely correct but it seems to at least work. May try emailing the original authors for a full answer though.

**Comment by rosinality** [comment]
I suspect that bottom level decoder takes only bottom level features and mid level quantized features, and mid level decoders take mid level features and top level quantized features, as it is more similar to common feature pyramid designs.

But it will be in the area of guess. Actually two stage layout from this repository is also a kind of guess. In the algorithm description in the paper it looks like that E_top and E_bottom is independent encoder, as it only takes input x, and not the feature from previous level encoders. But in the diagram, it looks like that top level encoder takes the feature of previous levels.

**Comment by vvvm23** [comment]
It is a little strange, there is a lot of guesswork involved. I imagine it is the case that the top encoder takes the features from the previous level. But it is less clear what features the decoder takes. I'm going to try an implementation that takes all the previous quantized features and see how well it works.

**Comment by vvvm23** [comment]
Oh, might be appropriate for me to close this also, since the conclusion is that it has to be guesswork ~
