### ISSUE TITLE
Dataset format problems

### ISSUE THREAD

**Issue by easonoob** [rosinality/vq-vae-2-pytorch#74]
I just cloned this repo and tried to train a model. I have a dataset folder that consists of about 30k different sizes (from 256 to 1024) .jpg images. When I run the command `python train_vqvae.py dataset` there was an error: `FileNotFoundError: Couldn't find any class folder in dataset.` What format does the dataset need to be?

**Comment by mw66** [comment]
@easonoob facing the same issue right now, can you share your experience? or pointing to some sample image data? Thanks.
